# Generated by Django 4.1.1 on 2023-08-15 05:24

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jwt_auth", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bill_amount", models.IntegerField(default=0)),
                ("ordered_at", models.DateTimeField(auto_now_add=True)),
                ("address", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("In the Kitchen", "In the Kitchen"),
                            ("Prepared", "Prepared"),
                            ("Out for Delivery", "Out for Delivery"),
                            ("Delivered", "Delivered"),
                        ],
                        default="Pending",
                        max_length=40,
                    ),
                ),
                (
                    "ordered_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer",
                        to="jwt_auth.customer",
                    ),
                ),
            ],
            options={
                "db_table": "Order",
            },
        ),
        migrations.CreateModel(
            name="Pizza",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("Slice", "Slice"),
                            ("Small", "Small"),
                            ("Medium", "Medium"),
                            ("Large", "Large"),
                            ("Giant", "Giant"),
                            ("Monster", "Monster"),
                        ],
                        default="Small",
                        max_length=40,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
                ("image", models.TextField()),
                (
                    "ingridients",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100), size=None
                    ),
                ),
                (
                    "description",
                    models.TextField(default="A Pizza to Have in Every Mood"),
                ),
            ],
            options={
                "db_table": "Pizza",
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pizza.order"
                    ),
                ),
                (
                    "pizza",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pizza.pizza"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="pizzas",
            field=models.ManyToManyField(through="pizza.OrderItem", to="pizza.pizza"),
        ),
    ]
