# Generated by Django 4.1.1 on 2023-08-15 11:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pizza", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="pizzas",
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
        migrations.AddField(
            model_name="order",
            name="pizzas",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.JSONField(), default=None, size=None
            ),
            preserve_default=False,
        ),
    ]
